// Roy Okola Otieno's master profile, imported via a seed mechanism (never
// hard-coded into business logic). Every fact is marked `user_provided` and is
// fully editable from the Profile screen. Source: the Rauell OS specification.

export const SEED = {
  user: {
    email: process.env.SEED_EMAIL || "roy@rauell.systems",
    name: process.env.SEED_NAME || "Roy Okola Otieno",
    // No default. A checked-in password becomes a real credential the moment
    // anyone runs the seed against a reachable deployment, so the seed script
    // requires SEED_PASSWORD to be supplied explicitly and refuses to run
    // without it.
    password: process.env.SEED_PASSWORD || "",
  },
  profile: {
    headline:
      "Agricultural & Biosystems Engineer | Renewable Energy, EV Infrastructure & Water Systems",
    summary:
      "Kenyan engineering and operations professional working across renewable energy, electric mobility, water systems and digital engineering tools. Builds decision-support platforms (SafariCharge / Solar Simulation Platform) and operates the wider Rauell Systems ecosystem. Combines field engineering, technical sales, and product-building experience.",
    location: "Nairobi, Kenya",
    nationality: "Kenyan",
    linkedin_url: "",
    portfolio_url: "https://rauell.systems",
  },
  education: [
    {
      institution: "Jomo Kenyatta University of Agriculture and Technology (JKUAT)",
      degree: "BSc",
      field: "Agricultural and Biosystems Engineering",
      start_year: 2018,
      end_year: 2024,
      status: "graduated",
      details: {
        classification: "Second Class Honours, Upper Division",
        focus: ["Renewable energy", "Water systems", "Irrigation", "Energy systems", "Engineering design"],
        finalProject:
          "Solar evaporative cooling for tomatoes - demonstrated >40% produce shelf-life improvement.",
      },
    },
    {
      institution: "University of East London (via Unicaf)",
      degree: "MBA (in progress)",
      field: "Business Administration",
      start_year: 2025,
      end_year: null,
      status: "in_progress",
      details: {
        topics: ["Strategy", "Operations", "HRM", "Industry 5.0", "Leadership", "Business analysis", "Alliance strategy", "Executive decision-making"],
      },
    },
    {
      institution: "FRED Energy Training Programme",
      degree: "Certificate",
      field: "Energy Systems",
      start_year: null,
      end_year: null,
      status: "training",
      details: {
        topics: ["Energy Systems Fundamentals", "Data Collection & Cleaning", "Techno-economic Modelling (HOMER, SAM)", "Energy Systems Design", "Reporting & Visualization", "Technical Asset Management"],
      },
    },
    {
      institution: "Torchbearer Institute",
      degree: "Certificate",
      field: "Solar PV",
      start_year: null,
      end_year: null,
      status: "training",
      details: { topics: ["Solar PV design and installation"] },
    },
    {
      institution: "RCMRD",
      degree: "Certificate",
      field: "GIS",
      start_year: null,
      end_year: null,
      status: "training",
      details: { topics: ["Geographic Information Systems"] },
    },
    {
      institution: "Tech4Good",
      degree: "Certificate",
      field: "ESG",
      start_year: null,
      end_year: null,
      status: "training",
      details: { topics: ["ESG fundamentals"] },
    },
    {
      institution: "Ebara / TUMI / PEM Motion / AMC",
      degree: "Certificate",
      field: "Pumps / E-Mobility",
      start_year: null,
      end_year: null,
      status: "training",
      details: { topics: ["Ebara pump technology", "Electric mobility", "TUMI mobility", "PEM Motion", "AMC e-mobility"] },
    },
  ],
  organizations: [
    { name: "Rauell Systems", type: "company", industry: "Software / Energy", location: "Kenya", website: "https://rauell.systems", notes: "Roy's wider digital ecosystem." },
    { name: "Roam Electric", type: "employer", industry: "Electric Mobility", location: "Nairobi, Kenya", website: "", notes: "EV charging infrastructure, technical sales & operations." },
    { name: "Frisco Engineering Ltd", type: "employer", industry: "Water / Boreholes", location: "Kenya", website: "", notes: "Off-grid borehole and groundwater engineering." },
    { name: "HomeBiogas Kenya", type: "employer", industry: "Biogas / Clean Energy", location: "Kenya", website: "", notes: "Technical Sales Engineer Intern." },
    { name: "JKUAT", type: "university", industry: "Education", location: "Kenya", website: "https://www.jkuat.ac.ke", notes: "Alma mater." },
    { name: "University of East London", type: "university", industry: "Education", location: "United Kingdom", website: "https://www.uel.ac.uk", notes: "MBA via Unicaf." },
    { name: "Greenwave Society", type: "nonprofit", industry: "Environment / Youth", location: "Kenya", website: "https://greenwavesociety.org", notes: "Youth-led environmental organization." },
    { name: "Kenya Youth Parliament for Water (KYPW)", type: "nonprofit", industry: "Water / Youth", location: "Kenya", website: "", notes: "Event coordination role." },
    { name: "SafariCharge", type: "product", industry: "Energy Software", location: "Kenya", website: "https://safaricharge.rauell.systems", notes: "Solar simulation & energy planning platform." },
  ],
  employment: [
    {
      orgName: "Roam Electric",
      title: "Technical Sales & Operations Engineer",
      role_category: "EV Infrastructure",
      start_date: "2022-01-01",
      end_date: null,
      current: 1,
      location: "Nairobi, Kenya",
      summary:
        "Technical sales, charging infrastructure deployment, energy operations, site assessment and rollout coordination for EV charging networks.",
      responsibilities: [
        "EV charging infrastructure (Roam Point, Roam Hub, fast & slow charging)",
        "Site vetting, assessment, feasibility and meter separation",
        "Partner engagement and outreach (Be Energy, Trinity Energy, Atlas pilots)",
        "Deployment coordination, training coordination, permits & stakeholder liaison",
        "CAPEX planning, infrastructure forecasting, investor communication",
        "Commercial negotiations and charging-network planning",
      ],
    },
    {
      orgName: "Frisco Engineering Ltd",
      title: "Field Engineer (Boreholes & Water Systems)",
      role_category: "Water Systems",
      start_date: "2021-01-01",
      end_date: null,
      current: 1,
      location: "Kenya (remote field sites)",
      summary:
        "Off-grid borehole and groundwater engineering including assessment, rehabilitation and troubleshooting in remote environments.",
      responsibilities: [
        "Borehole assessment, pump troubleshooting and rehabilitation",
        "Camera inspection, flushing recommendations, pump & flow-rate testing",
        "Depth assessment, motor & electrical winding evaluation",
        "Engineering recommendations, costing and client communication",
        "Project contexts: Mara off-grid sites, Zuri Prime Farms, Notre Dame borehole works",
      ],
    },
    {
      orgName: "HomeBiogas Kenya",
      title: "Technical Sales Engineer Intern",
      role_category: "Renewable Energy",
      start_date: "2020-01-01",
      end_date: "2020-12-31",
      current: 0,
      location: "Kenya",
      summary: "Biogas systems, household renewable energy, technical sales and customer engagement.",
      responsibilities: ["Biogas systems", "Household renewable energy", "Technical sales", "Customer engagement", "Clean energy advisory"],
    },
  ],
  skills: [
    { name: "Solar PV", category: "Energy", proficiency: "Advanced", years: 4, evidence: ["Roam Electric", "Solar evaporative cooling project", "Torchbearer Institute"] },
    { name: "Battery Storage", category: "Energy", proficiency: "Proficient", years: 3, evidence: ["Roam Electric", "SafariCharge"] },
    { name: "EV Charging Infrastructure", category: "Mobility", proficiency: "Advanced", years: 3, evidence: ["Roam Electric"] },
    { name: "Site Assessment & Feasibility", category: "Operations", proficiency: "Advanced", years: 3, evidence: ["Roam Electric"] },
    { name: "Technical Sales", category: "Commercial", proficiency: "Advanced", years: 4, evidence: ["Roam Electric", "HomeBiogas Kenya"] },
    { name: "Water Systems & Boreholes", category: "Water", proficiency: "Advanced", years: 3, evidence: ["Frisco Engineering Ltd"] },
    { name: "Pump Systems", category: "Water", proficiency: "Proficient", years: 3, evidence: ["Frisco Engineering Ltd"] },
    { name: "Energy Modelling", category: "Energy", proficiency: "Proficient", years: 2, evidence: ["FRED training", "SafariCharge"] },
    { name: "Techno-economic Analysis (HOMER, SAM)", category: "Energy", proficiency: "Proficient", years: 2, evidence: ["FRED training"] },
    { name: "Renewable Energy Systems", category: "Energy", proficiency: "Advanced", years: 4, evidence: ["Roam Electric", "HomeBiogas Kenya", "JKUAT"] },
    { name: "Energy Data & Analytics", category: "Data", proficiency: "Proficient", years: 2, evidence: ["SafariCharge"] },
    { name: "Software / Product Building", category: "Software", proficiency: "Developing", years: 2, evidence: ["Rauell Systems", "SafariCharge"] },
    { name: "Python", category: "Software", proficiency: "Developing", years: 1, evidence: ["SafariCharge analytics", "AI experiments"] },
    { name: "GIS", category: "Tools", proficiency: "Basic", years: 1, evidence: ["RCMRD training"] },
    { name: "Project Coordination", category: "Operations", proficiency: "Advanced", years: 4, evidence: ["Roam Electric", "KYPW"] },
    { name: "Stakeholder Engagement", category: "Commercial", proficiency: "Advanced", years: 4, evidence: ["Roam Electric", "Greenwave Society"] },
    { name: "Agile / Field Engineering", category: "Operations", proficiency: "Proficient", years: 3, evidence: ["Frisco Engineering Ltd", "Roam Electric"] },
  ],
  projects: [
    {
      name: "SafariCharge / Solar Simulation Platform",
      category: "Product",
      status: "active",
      overview:
        "Solar simulation and energy planning platform. Models PV, inverters, batteries and EV charging with tariff-aware, deterministic, reproducible simulations and decision-ready reporting.",
      goals: ["Describe the site", "Model demand", "Compare systems", "Explain the recommendation", "Share the decision"],
      nextActions: ["Add borehole/groundwater module", "Ship Battery Health Score", "Publish API docs"],
    },
    {
      name: "Rauell Systems Ecosystem",
      category: "Company",
      status: "active",
      overview: "Umbrella for Roy's digital products: portfolio, CV system, AI learning tools, organizational platforms and engineering dashboards.",
      goals: ["Consolidate products under one brand", "Launch Rauell OS"],
      nextActions: ["Finalize branding", "Connect product portfolio"],
    },
    {
      name: "AI Academy",
      category: "Learning",
      status: "active",
      overview: "Responsive AI learning platform with course catalogue, pathways, lesson player, labs and a contextual RAG tutor.",
      goals: ["Auth + Neon persistence", "Quizzes & certificates", "RAG tutor"],
      nextActions: ["Define curriculum schema", "Wire learner progress"],
    },
    {
      name: "Personal Portfolio",
      category: "Portfolio",
      status: "active",
      overview: "Professional portfolio demonstrating engineering, renewable energy, water, mobility and digital systems work.",
      goals: ["Showcase SafariCharge", "Evidence-based project cards"],
      nextActions: ["Add case studies"],
    },
    {
      name: "Greenwave Society",
      category: "Volunteer",
      status: "active",
      overview: "Youth-led environmental organization: events, branding, digital systems and environmental communication.",
      goals: ["Grow youth engagement", "Strengthen digital presence"],
      nextActions: ["Plan next quarterly event"],
    },
    {
      name: "Kenya Youth Parliament for Water",
      category: "Volunteer",
      status: "active",
      overview: "Event coordination: webinars, workshops, hackathons, dialogues and field visits for the water sector.",
      goals: ["Quarterly planning", "Partnership coordination"],
      nextActions: ["Confirm next workshop date"],
    },
  ],
  goals: [
    { title: "Secure a fully funded Master's programme", description: "Renewable Energy / Energy Systems / Sustainable Energy (Erasmus Mundus, Mastercard Foundation, etc.)." },
    { title: "Advance renewable-energy engineering career", description: "Target roles in solar, energy systems, EV infrastructure and energy data." },
    { title: "Develop SafariCharge", description: "Grow the solar simulation & energy planning platform into a marketable product." },
    { title: "Generate consulting leads", description: "Solar feasibility, energy planning, EV charging planning, water infrastructure." },
    { title: "Expand professional network", description: "Strengthen relationships across energy, mobility, water and climate sectors." },
    { title: "Improve AI & software capabilities", description: "Deepen Python, data and product-building skills for engineering software." },
  ],
  opportunities: [
    {
      type: "programme",
      title: "Erasmus Mundus Joint Master's in Renewable Energy (EMSREN / similar)",
      orgName: "European Commission / Consortium Universities",
      source_url: "https://www.eu-emenu.org",
      description:
        "Fully funded joint Master's across multiple European universities in renewable energy engineering. Includes tuition, living and travel allowances.",
      deadline: null,
      location: "Europe",
      remote: false,
      compensation: "Fully funded (tuition, living, travel)",
      structured: {
        funding: "fully funded",
        tuitionCovered: true,
        livingAllowance: true,
        travelAllowance: true,
        englishRequirement: "waiver possible (English-taught programmes)",
        admissionCompetitiveness: "high",
        careerRelevance: 95,
        field: "renewable energy",
      },
    },
    {
      type: "scholarship",
      title: "Mastercard Foundation Scholars Program",
      orgName: "Mastercard Foundation",
      source_url: "https://mastercardfdn.org",
      description:
        "Scholarship for African students to pursue graduate studies at partner universities, covering tuition, living costs and travel.",
      deadline: null,
      location: "Various (Africa / partner universities)",
      remote: false,
      compensation: "Fully funded",
      structured: {
        funding: "fully funded",
        tuitionCovered: true,
        livingAllowance: true,
        travelAllowance: true,
        englishRequirement: "required",
        admissionCompetitiveness: "very high",
        careerRelevance: 92,
        field: "renewable energy / engineering",
      },
    },
    {
      type: "job",
      title: "Renewable Energy Engineer",
      orgName: "Confidential (sample)",
      source_url: null,
      description:
        "Design and deploy solar PV and battery storage systems. Requires experience with renewable energy systems, technical sales and site assessment.",
      deadline: null,
      location: "Nairobi, Kenya",
      remote: false,
      compensation: "Competitive",
      structured: {
        requirements: ["solar pv", "battery storage", "energy systems", "technical sales", "site assessment"],
        sector: "renewable energy",
        seniority: "mid",
      },
    },
  ],
  tasks: [
    { title: "Review Erasmus Mundus eligibility and document checklist", priority: 4, status: "inbox", source: "seed", due_in_days: 6, effort: "1h", strategic: true },
    { title: "Follow up with referee on recommendation letter", priority: 4, status: "inbox", source: "seed", due_in_days: 4, effort: "15m", strategic: true },
    { title: "Update SafariCharge battery health score module", priority: 3, status: "next", source: "seed", due_in_days: 9, effort: "4h", strategic: false },
    { title: "Draft weekly project review", priority: 2, status: "inbox", source: "seed", due_in_days: 2, effort: "30m", strategic: false },
  ],
} as const;
